# Generated by Django 5.0.7 on 2024-08-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_is_2fa_enabled_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tier_type",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
