# Generated by Django 5.0.7 on 2024-08-02 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaign_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="kpis",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="priority",
            field=models.CharField(
                choices=[("high", "High"), ("mid", "Mid"), ("low", "Low")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("archived", "Archived"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
