# Generated by Django 5.0.7 on 2024-08-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_campaign_user_alter_campaign_campaign_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("interaction_date", models.DateTimeField()),
                ("job_position", models.CharField(max_length=255)),
                ("linkedin_profile_url", models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="history",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="progress",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="settings",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="interacted_users",
            field=models.ManyToManyField(
                related_name="campaigns", to="campaigns.interacteduser"
            ),
        ),
    ]
