# Generated by Django 5.0.7 on 2024-08-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_campaign_campaign_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="campaign_id",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="id",
            field=models.CharField(
                default="",
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
