# Generated by Django 5.0.7 on 2024-08-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_remove_campaign_campaign_id_alter_campaign_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="tier_type",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
