# Generated by Django 5.0.7 on 2024-08-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_campaign_tier_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="campaign_type",
            field=models.CharField(
                choices=[
                    ("profile_stalker", "Profile Stalker"),
                    ("content_finder", "Content Finder"),
                    ("profile_finder", "Profile Finder"),
                    ("targeted_commentor", "Targeted Commentor"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
