# Generated by Django 5.0.7 on 2024-08-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0007_alter_campaign_campaign_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="kpis",
        ),
    ]
