# Generated by Django 5.0.7 on 2024-08-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0008_remove_campaign_kpis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="settings",
        ),
    ]
