# Generated by Django 5.0.7 on 2024-08-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0011_remove_campaign_tier_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="comment_threashold",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="formality_level",
            field=models.CharField(
                choices=[("formal", "Formal"), ("informal", "InFormal")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="gSheet_input",
            field=models.FileField(null=True, upload_to="gsheets/"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="hashtags",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="manual_approval",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="target_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("zh", "Chinese"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="tonality",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="use_emoji",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], max_length=255, null=True
            ),
        ),
    ]
