# Generated by Django 5.0.7 on 2024-08-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "campaigns",
            "0012_campaign_comment_threashold_campaign_formality_level_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="interacted_users",
            field=models.ManyToManyField(
                null=True, related_name="campaigns", to="campaigns.interacteduser"
            ),
        ),
    ]
