# Generated by Django 5.0.7 on 2024-08-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0014_campaign_auto_answer_incoming_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="interacted_users",
            field=models.ManyToManyField(
                related_name="campaigns", to="campaigns.interacteduser"
            ),
        ),
    ]
