# Generated by Django 5.0.7 on 2024-08-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0016_alter_interacteduser_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="interacted_users",
            field=models.ManyToManyField(
                blank=True, related_name="campaigns", to="campaigns.interacteduser"
            ),
        ),
    ]
