# Generated by Django 5.0.7 on 2024-08-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0019_alter_campaign_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="published_date_threashhold",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="question_frequency",
            field=models.IntegerField(null=True),
        ),
    ]
